//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiteCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItem()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public short MenuItemID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public short CategoryID { get; set; }
        public Nullable<System.DateTime> AvailabilityStartDate { get; set; }
        public Nullable<System.DateTime> AvailabilityEndDate { get; set; }
        public Nullable<System.TimeSpan> AvailabilityStartTime { get; set; }
        public Nullable<System.TimeSpan> AvailabilityEndTime { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual MenuCategory MenuCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
