//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiteCafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public short OrderItemID { get; set; }
        public short TransactionId { get; set; }
        public short MenuItemId { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual Order Order { get; set; }
    }
}
